spring:
  output:
    ansi:
      enabled: detect

  application:
    name: overview

  datasource:
    url: jdbc:h2:mem:overview
    username: sa
    password: password
    driverClassName: org.h2.Driver

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      format_sql: true
      ddl-auto: validate

ov:
  api:
    base-url: /api/overview-server/v1/

springdoc:
  swagger-ui:
    path: /swagger
